db_file "~/.config/mpd/database"

music_directory "~/Music"
playlist_directory "~/Music/playlists"

audio_output {
    type "alsa"
    name "alsa sound"
}

audio_output {
    type "fifo"
    name "Visualizer feed"
    path "/tmp/mpd.fifo"
    format "44100:16:2"
}
