#!/usr/bin/env bash 

wifi='🌐'
no_wifi='✈︎'

wifi_status=$(cat /sys/class/net/wlp4s0/operstate)
wifi_signal=$(iw dev wlp4s0 link | grep -i signal )

if [[ "$wifi_status" == "up" ]]; then
    echo "$wifi"
elif [[ "$wifi_status" == "down" ]]; then
    echo "$no_wifi"
else 
    echo "broken"
fi
    
# echo "signal: ${wifi_signal}"

