#!/usr/bin/env bash

wifi_status=$(cat /sys/class/net/wlp4s0/operstate 2>/dev/null)

if [[ "$wifi_status" == "up" ]]; then
    signal=$(iw dev wlp4s0 link 2>/dev/null | awk '/signal/ {print $2}')
    if (( signal > -50 )); then
        bars="[###]"
    elif (( signal > -70 )); then
        bars="[##]"
    else
        bars="[#]"
    fi
    echo "$bars"
else
    echo "---"
fi

